apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <APPLICATIONNAME>-pvc-device-data
  namespace: <NAMESPACE>
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: local-path
  resources:
    requests:
      storage: 1Mi
