apiVersion: apps/v1
kind: Deployment
metadata:
  name:  <APPLICATIONNAME>
  namespace: <NAMESPACE>
  labels:
    app: oisp-testsensor-sensor
spec:
  selector:
    matchLabels:
      app: oisp-testsensor-sensor
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oisp-testsensor-sensor
    spec:
      containers:
      - name: oisp-iot-agent
        env:
          - name: OISP_DEVICE_ID
            value: "<APPLICATIONNAME>"
          - name: OISP_DEVICE_ACTIVATION_CODE
            valueFrom:
              secretKeyRef:
                name: global-devices-secret
                key: activation-code
        volumeMounts:
          - name: oisp-devices-config-volume
            mountPath: /volume/config
          - name: oisp-devices-data-volume
            mountPath: /volume/data
        image: docker.io/oisp/oisp-iot-agent:v2.1.3
        imagePullPolicy: IfNotPresent
      - name: oisp-testsensor
        image: docker.io/spandey21/openvino_model_client:v0.1
        imagePullPolicy: IfNotPresent
        securityContext:
           privileged: true
        env:
          - name: LOG_LEVEL
            value: "verbose"
        volumeMounts:
          - name: testsensor-config
            mountPath: /etc/oisp
          - name: dev-video0
            mountPath: /dev/video0
        resources:
          limits:
      volumes:
        - name: oisp-devices-config-volume
          configMap:
            name: global-devices-config
            items:
            - key: config.json
              path: config.json
        - name: testsensor-config
          configMap:
            name: <APPLICATIONNAME>-testsensor-config
            items:
            - key: sensorSpecs.json
              path: sensorSpecs.json
        - name: oisp-devices-data-volume
          persistentVolumeClaim:
            claimName: <APPLICATIONNAME>-pvc-device-data
        - name: dev-video0
          hostPath:
            path: /dev/video0
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: <NODENAME>
      imagePullSecrets:
      - name: regcred
