apiVersion: apps/v1
kind: Deployment
metadata:
  name:  <APPLICATIONNAME>
  namespace: <NAMESPACE>
  labels:
    app: <APPLICATIONNAME>-oisp-testsensor-sensor
spec:
  selector:
    matchLabels:
      app: <APPLICATIONNAME>-oisp-testsensor-sensor
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: <APPLICATIONNAME>-oisp-testsensor-sensor
    spec:
      containers:
      - name: oisp-iot-agent
        env:
          - name: OISP_DEVICE_ID
            value: "<APPLICATIONNAME>"
          - name: OISP_DEVICE_ACTIVATION_CODE
            valueFrom:
              secretKeyRef:
                name: <APPLICATIONNAME>-global-devices-secret
                key: activation-code
        volumeMounts:
          - name: oisp-devices-config-volume
            mountPath: /volume/config
          - name: oisp-devices-data-volume
            mountPath: /volume/data
        image: docker.io/ibn40/oisp-iot-agent:v2.3.0
        imagePullPolicy: Always
      - name: oisp-testsensor
        image: docker.io/ibn40/oisp-testsensor:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: LOG_LEVEL
            value: "verbose"
        volumeMounts:
          - name: testsensor-config
            mountPath: /etc/oisp
        resources:
           requests:
              memory: "32Mi"
           limits:
              memory: "128Mi"
      volumes:
        - name: oisp-devices-config-volume
          configMap:
            name: <APPLICATIONNAME>-global-devices-config
            items:
            - key: config.json
              path: config.json
        - name: testsensor-config
          configMap:
            name: <APPLICATIONNAME>-testsensor-config
            items:
            - key: sensorSpecs.json
              path: sensorSpecs.json
        - name: oisp-devices-data-volume
          persistentVolumeClaim:
            claimName: <APPLICATIONNAME>-pvc-device-data
      nodeSelector:
        kubernetes.io/hostname: <NODENAME>
      imagePullSecrets:
      - name: regcred
